kind: Service			#    --> Defines to create service type object
apiVersion: v1
metadata:
  name: demoservice
spec:
  ports:
    - port: 80			#    --> Containers port exposed
      targetPort: 80		#--> Pods port
  selector:
    name: deployment		#--> Apply this service to any pods which has the specific label
  type: NodePort		 #  --> Specifies the service type i.e. ClusterIP or NodePort
